---
kind: pipeline
name: build

clone:
  depth: 50

steps:
  - name: publish
    image: plugins/docker
    settings:
      repo: lukasbahr/prometheus-fritzdect-exporter
      tags: 
        - ${DRONE_TAG}
      dockerfile: Dockerfile
      username:
        from_secret: REGISTRY_USER
      password:
        from_secret: REGISTRY_PASSWORD
      build_args:
        - DRONE_TAG=${DRONE_TAG}
    when:
      event:
        - push
        - tag